name: Build e Teste do App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependências
      run: npm ci

    - name: Rodar o Build do Projeto
      run: npm run build --if-present

    - name: Disponibilizar o arquivo para download
      uses: actions/upload-artifact@v4
      with:
        name: app-otimizador-build
        path: dist/ # Se o seu build gerar outra pasta que não seja 'dist' (como 'build' ou 'out'), mude aqui.
